# fly.toml app configuration file generated for django-party on 2025-04-21T10:09:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-party'
primary_region = 'lax'
console_command = '/home/app/web/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/home/app/web/static'
  url_prefix = '/static/'
